# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
          echo 'install foundry' # runs during prebuild
          curl -L https://foundry.paradigm.xyz | bash
          source /home/gitpod/.bashrc
          foundryup
    command: forge install zobront/xchain
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
